fix(ci): add testnet flow (#547)

diff --git a/.github/workflows/build-deploy.yaml b/.github/workflows/build-deploy.yaml
--- a/.github/workflows/build-deploy.yaml
+++ b/.github/workflows/build-deploy.yaml
@@ -59,18 +59,15 @@ jobs:
 
       - name: Set image output
         id: set_image_output
-        run: echo "${{ github.sha }}" >> $GITHUB_ENV
-
-      - name: Check for updates
-        id: check_updates
         run: |
-          echo "IMAGE_CHANGED=true" >> $GITHUB_ENV
           if [[ "${{ steps.docker_build.outcome }}" == "success" ]]; then
             echo "${{ matrix.service }}=${{ github.sha }}" >> $GITHUB_OUTPUT
           else
-            echo "No changes detected for ${{ matrix.service }}."
             echo "${{ matrix.service }}=false" >> $GITHUB_OUTPUT
           fi
+
+    outputs:
+      matrix-result: ${{ toJSON(steps.set_image_output.outputs) }}
 
   deploy:
     needs: build
@@ -89,92 +86,103 @@ jobs:
           echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
           echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV
 
-      - name: Deploy to testnet
+      - name: Deploy and verify testnet
         run: |
-          # Set context to the testnet namespace
           kubectl config set-context --current --namespace=nearblocks-testnet
 
           services=(api app app-lite backend indexer-balance indexer-base indexer-events indexer-dex explorer-selector aggregates)
+          failed_deployments=()
 
           for service in "${services[@]}"; do
-            service_changed=${{ needs.build.outputs[service] }}
+            service_sha=$(echo '${{ needs.build.outputs.matrix-result }}' | jq -r ".[\"$service\"]")
             
-            if [[ "$service_changed" != "false" ]]; then
+            if [[ "$service_sha" != "false" && "$service_sha" != "null" ]]; then
               deployment_name="testnet-$service"
               echo "Updating deployment for $deployment_name"
-              kubectl set image deployment/$deployment_name $service=ghcr.io/nearblocks/$service:${{ needs.build.outputs[service] }}
+              kubectl set image deployment/$deployment_name $service=ghcr.io/nearblocks/$service:$service_sha
+
+              echo "Verifying rollout for $deployment_name"
+              if ! kubectl rollout status deployment/$deployment_name --timeout=300s; then
+                echo "Rollout failed for $deployment_name"
+                failed_deployments+=("$deployment_name")
+              fi
             else
               echo "Skipping deployment for testnet-$service (no updates)"
             fi
           done
 
-      - name: Verify rollout for testnet
-        run: |
-          services=(api app app-lite backend indexer-balance indexer-base indexer-events indexer-dex explorer-selector aggregates)
-          for service in "${services[@]}"; do
-            service_changed=${{ needs.build.outputs[service] }}
-            
-            if [[ "$service_changed" != "false" ]]; then
-              deployment_name="testnet-$service"
-              echo "Verifying rollout for $deployment_name"
-              if ! kubectl rollout status deployment/$deployment_name --timeout=300s; then
-                echo "Rollout failed for $deployment_name"
-                failed_rollouts+=("$deployment_name")
-              fi
-            fi
-          done
+          if [ ${#failed_deployments[@]} -ne 0 ]; then
+            echo "The following deployments failed:"
+            printf '%s\n' "${failed_deployments[@]}"
+            exit 1
+          fi
 
-      - name: Rollback failed deployments
+      - name: Rollback failed testnet deployments
         if: failure()
         run: |
+          kubectl config set-context --current --namespace=nearblocks-testnet
+
           services=(api app app-lite backend indexer-balance indexer-base indexer-events indexer-dex explorer-selector aggregates)
 
           for service in "${services[@]}"; do
-            service_changed=${{ needs.build.outputs[service] }}
+            service_sha=$(echo '${{ needs.build.outputs.matrix-result }}' | jq -r ".[\"$service\"]")
             
-            if [[ "$service_changed" != "false" ]]; then
+            if [[ "$service_sha" != "false" && "$service_sha" != "null" ]]; then
               deployment_name="testnet-$service"
               echo "Attempting rollback for $deployment_name"
               kubectl rollout undo deployment/$deployment_name
             fi
           done
 
-      - name: Notify on failure
-        if: failure()
-        run: |
-          echo "Deployment failed. Manual intervention may be required."
-
-      # - name: Deploy to mainnet
+      # - name: Deploy and verify mainnet
       #   run: |
-      #     # Set context to the mainnet namespace
       #     kubectl config set-context --current --namespace=nearblocks
 
       #     services=(api app app-lite backend indexer-balance indexer-base indexer-events indexer-dex explorer-selector aggregates)
+      #     failed_deployments=()
 
       #     for service in "${services[@]}"; do
-      #       service_changed=${{ needs.build.outputs[service] }}
-
-      #       if [[ "$service_changed" != "false" ]]; then
+      #       service_sha=$(echo '${{ needs.build.outputs.matrix-result }}' | jq -r ".[\"$service\"]")
+            
+      #       if [[ "$service_sha" != "false" && "$service_sha" != "null" ]]; then
       #         deployment_name="mainnet-$service"
       #         echo "Updating deployment for $deployment_name"
-      #         kubectl set image deployment/$deployment_name $service=ghcr.io/nearblocks/$service:${{ needs.build.outputs[service] }}
+      #         kubectl set image deployment/$deployment_name $service=ghcr.io/nearblocks/$service:$service_sha
+
+      #         echo "Verifying rollout for $deployment_name"
+      #         if ! kubectl rollout status deployment/$deployment_name --timeout=300s; then
+      #           echo "Rollout failed for $deployment_name"
+      #           failed_deployments+=("$deployment_name")
+      #         fi
       #       else
       #         echo "Skipping deployment for mainnet-$service (no updates)"
       #       fi
       #     done
 
-      # - name: Verify rollout for mainnet
-      #   run: |
-      #     services=(api app app-lite backend indexer-balance indexer-base indexer-events indexer-dex explorer-selector aggregates)
-      #     for service in "${services[@]}"; do
-      #       service_changed=${{ needs.build.outputs[service] }}
+      #     if [ ${#failed_deployments[@]} -ne 0 ]; then
+      #       echo "The following deployments failed:"
+      #       printf '%s\n' "${failed_deployments[@]}"
+      #       exit 1
+      #     fi
 
-      #       if [[ "$service_changed" != "false" ]]; then
+      # - name: Rollback failed mainnet deployments
+      #   if: failure()
+      #   run: |
+      #     kubectl config set-context --current --namespace=nearblocks
+
+      #     services=(api app app-lite backend indexer-balance indexer-base indexer-events indexer-dex explorer-selector aggregates)
+
+      #     for service in "${services[@]}"; do
+      #       service_sha=$(echo '${{ needs.build.outputs.matrix-result }}' | jq -r ".[\"$service\"]")
+            
+      #       if [[ "$service_sha" != "false" && "$service_sha" != "null" ]]; then
       #         deployment_name="mainnet-$service"
-      #         echo "Verifying rollout for $deployment_name"
-      #         if ! kubectl rollout status deployment/$deployment_name --timeout=300s; then
-      #           echo "Rollout failed for $deployment_name"
-      #           failed_rollouts+=("$deployment_name")
-      #         fi
+      #         echo "Attempting rollback for $deployment_name"
+      #         kubectl rollout undo deployment/$deployment_name
       #       fi
       #     done
+
+      - name: Notify on failure
+        if: failure()
+        run: |
+          echo "Deployment failed. Manual intervention may be required."
